server:
  port: 8080

spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9a510.p.ssafy.io:3306/test?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/root?serverTimezone=Asia/Seoul
    username: A510
    password: 3jbhrVyqstWs9ud
    # JPA
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #성능 최적화


jwt:
  secretKey: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

#oauth:
#  kakao:
#    client-id: c5946728a9bb2c5f333e060a4c8a97d3
#    url:
#      auth: https://kauth.kakao.com
#      api: https://kapi.kakao.com
