
server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: j9a510.p.ssafy.io
    port: 6379
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9a510.p.ssafy.io:3306/temp?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/tenten?serverTimezone=Asia/Seoul
    username: A510
    password: 3jbhrVyqstWs9ud
    # JPA
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #성능 최적화

jwt:
  secretKey: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K
  access:
    expiration: 36000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization_refresh