spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c5946728a9bb2c5f333e060a4c8a97d3
#            redirect-uri: http://www.jeongchaegi.com:8081/login/oauth2/code/kakao
            redirect-uri: http://localhost:8080/api/vi/oauth2/kakao
            client-authentication-method: POST
            client-secret: pRSA14TOtuEjc9Q6Ghb0ppyXnBcJi9Wz
            authorization-grant-type: authorization_code
            #response-type: code

            scope:
              - profile_nickname
              - account_email
              - profile_image
            client_name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id